#!/bin/sh
set -e

# Enhanced Universal Logging Platform - Docker Entrypoint
# Handles first-time setup and normal server operations

echo "🐳 Enhanced Universal Logging Platform - Docker Container Starting..."

# Check if this is first-time setup
SETUP_COMPLETE_FILE="/app/data/setup-complete.json"
ENV_FILE="/app/.env"

if [ ! -f "$SETUP_COMPLETE_FILE" ] || [ ! -f "$ENV_FILE" ]; then
    echo "🔧 First-time installation detected"
    
    # Check if AUTH_PASSWORD is set via environment variable
    if [ -n "$AUTH_PASSWORD" ]; then
        echo "✅ AUTH_PASSWORD found in environment - proceeding with automatic setup"
        
        # Create .env file with environment variables
        cat > /app/.env << EOF
# Enhanced Universal Logging Platform Configuration
# Auto-generated by Docker container on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Authentication
AUTH_PASSWORD=${AUTH_PASSWORD}
JWT_SECRET=${JWT_SECRET:-$(openssl rand -hex 32)}
SESSION_SECRET=${SESSION_SECRET:-$(openssl rand -hex 24)}

# Server Configuration  
PORT=${PORT:-3000}
NODE_ENV=${NODE_ENV:-production}
TZ=${TZ:-UTC}

# SSL Configuration
USE_HTTPS=${USE_HTTPS:-false}
SSL_CERT_PATH=${SSL_CERT_PATH:-/app/ssl/cert.pem}
SSL_KEY_PATH=${SSL_KEY_PATH:-/app/ssl/key.pem}

# Feature Flags
ENABLE_METRICS=${ENABLE_METRICS:-true}
ENABLE_ALERTING=${ENABLE_ALERTING:-true}
ENABLE_DISTRIBUTED_TRACING=${ENABLE_DISTRIBUTED_TRACING:-true}
ENABLE_ADVANCED_SEARCH=${ENABLE_ADVANCED_SEARCH:-true}

# Data Management
LOG_RETENTION_DAYS=${LOG_RETENTION_DAYS:-30}
CLEANUP_INTERVAL_HOURS=${CLEANUP_INTERVAL_HOURS:-24}
MAX_UPLOAD_SIZE_MB=${MAX_UPLOAD_SIZE_MB:-100}

# Performance
MAX_MEMORY_MB=${MAX_MEMORY_MB:-512}
MAX_CPU_PERCENT=${MAX_CPU_PERCENT:-80}
WORKER_PROCESSES=${WORKER_PROCESSES:-1}

# Security
BCRYPT_SALT_ROUNDS=${BCRYPT_SALT_ROUNDS:-12}
RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-900000}
RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS:-100}

# Database
DATABASE_PATH=${DATABASE_PATH:-/app/data/databases/logs.db}
ENABLE_DATABASE_BACKUP=${ENABLE_DATABASE_BACKUP:-true}
BACKUP_INTERVAL_HOURS=${BACKUP_INTERVAL_HOURS:-24}

# Logging
LOG_LEVEL=${LOG_LEVEL:-info}
LOG_TO_FILE=${LOG_TO_FILE:-true}
LOG_TO_CONSOLE=${LOG_TO_CONSOLE:-true}
LOG_MAX_FILE_SIZE=${LOG_MAX_FILE_SIZE:-10MB}
LOG_MAX_FILES=${LOG_MAX_FILES:-5}

# Integration
DEFAULT_TIMEZONE=${DEFAULT_TIMEZONE:-UTC}
DATE_FORMAT=${DATE_FORMAT:-YYYY-MM-DD HH:mm:ss}

# Docker-specific
HEALTH_CHECK_ENDPOINT=${HEALTH_CHECK_ENDPOINT:-/api/health}
GRACEFUL_SHUTDOWN_TIMEOUT=${GRACEFUL_SHUTDOWN_TIMEOUT:-30}
EOF

        # Set secure permissions on .env file (skip if bind-mounted from Windows)
        chmod 600 /app/.env 2>/dev/null || echo "⚠️  Could not chmod .env (bind-mounted from Windows - this is OK)"
        echo "✅ Environment configuration created"
        
        # Run proper database migration to ensure all tables exist with correct schema
        echo "📊 Running database migration..."
        node archive/migrations/database-migration.js
        
        # Mark setup as complete
        mkdir -p /app/data
        cat > "$SETUP_COMPLETE_FILE" << EOF
{
  "completedAt": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
  "method": "docker-auto-setup",
  "adminUsername": "admin",
  "adminEmail": "admin@enterprise.local",
  "serverPort": ${PORT:-3000},
  "version": "2.2.0-security-hardened",
  "dockerContainer": true
}
EOF
        echo "✅ Setup completion marker created"
        
        # Start server directly using npm start (handles setup if needed)
        echo "🚀 Starting Enhanced Universal Logging Platform..."
        exec npm start
        
    else
        echo "⚠️  No AUTH_PASSWORD environment variable found"
        echo "🎮 Starting interactive setup wizard..."
        echo ""
        echo "🌐 Please open http://localhost:10180 in your browser to complete setup"
        echo "📋 Or set AUTH_PASSWORD environment variable for automatic setup"
        echo ""
        
        # Start the setup wizard
        exec npm start
    fi
else
    echo "✅ Setup already completed - starting main server"
    # Setup is complete, start the main server
    exec pm2-runtime start server.js --name logging-server
fi